CREATE TABLE IF NOT EXISTS `fakeid` (
    `id` VARCHAR(100) NULL DEFAULT NULL, --
    `oldname` VARCHAR(50) NULL DEFAULT NULL,
    `newname` VARCHAR(32) NULL DEFAULT NULL,
    `type` VARCHAR(7) NULL DEFAULT NULL,
    `dob` VARCHAR(11) NULL DEFAULT NULL,
    `gender` VARCHAR(1) NULL DEFAULT NULL,
    `category` VARCHAR(25) NULL DEFAULT NULL,
    `height` VARCHAR(3) NULL DEFAULT NULL
);
